# Generated by Django 3.0.3 on 2020-12-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directMessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
