# Generated by Django 3.0.3 on 2020-12-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directMessage', '0003_conversations_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/img/default_img.png', upload_to='profile'),
        ),
    ]
